# Generated by Django 3.2.12 on 2022-04-19 01:49

import awx.main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_make_instance_cpu_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ansible_integrity_error',
            field=models.TextField(blank=True, default='', editable=False, help_text='Error message of ansible integrity'),
        ),
        migrations.AddField(
            model_name='job',
            name='ansible_integrity_reasoncode',
            field=models.CharField(blank=True, default='', editable=False, help_text='Reason code for ansible integrity result', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='ansible_integrity_timestamp',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='job',
            name='ansible_integrity_verified',
            field=models.BooleanField(blank=True, default=None, editable=False, help_text='Overall result of ansible integrity verification', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_instance_groups',
            field=awx.main.fields.JSONBlob(blank=True, default=list, help_text='A list of InstanceGroup names where container verification is configured'),
        ),
        migrations.AddField(
            model_name='project',
            name='ansible_integrity_enabled',
            field=models.BooleanField(blank=True, default=False, help_text='Enable integrity check for playbook, collections and execution environment'),
        ),
        migrations.AddField(
            model_name='project',
            name='collection_integrity_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Enable integrity check for collections and override the global flag', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='collection_integrity_latest_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='collection_integrity_public_keys',
            field=awx.main.fields.JSONBlob(blank=True, default=list, help_text='List of base64 encoded public keys or Credential IDs'),
        ),
        migrations.AddField(
            model_name='project',
            name='container_integrity_enabled',
            field=models.BooleanField(
                blank=True, default=None, help_text='Enable integrity check for execution environment container image and override the global flag', null=True
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Enable integrity check for playbook and override the global flag', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_latest_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_public_keys',
            field=awx.main.fields.JSONBlob(blank=True, default=list, help_text='List of base64 encoded public keys or Credential IDs'),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_signature_type',
            field=models.CharField(
                blank=True,
                choices=[('gpg', 'GPG'), ('sigstore', 'Sigstore')],
                default='gpg',
                help_text='A signature type for playbook integrity check',
                max_length=128,
                verbose_name='signature type for playbook integrity check',
            ),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='collection_integrity_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='playbook_integrity_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
    ]
