# Generated by Django 3.2.12 on 2022-04-14 11:28

import awx.main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_add_playbook_integrity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='execution_environment_allowed_instance_groups',
            field=awx.main.fields.JSONBlob(
                blank=True, default=[], help_text='A list of InstanceGroup names where execution environment verification is configured for this project'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='execution_environment_verification_enabled',
            field=models.BooleanField(blank=True, default=False, help_text='If true, integrity check for execution environment is enabled'),
        ),
    ]
